Repository demisto/dockerfiles, pull requests merged in 2024-06, with the labels that each got.

#27436 [asana] Revert Version
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
  docker/py3-tools/verify.py
Labels: native image approved

#27464 [py3-tools-ubi] Downgrade `asana`
  .github/dependabot.yml
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
Labels: native image approved

#27485 [Py3 Native] Update `py3-tools-ubi:1.0.0.96981`
  docker/py3-native/Dockerfile
Labels: native image approved

#27507 adding orionsdk to panwiot
  docker/panw-iot/Pipfile
  docker/panw-iot/Pipfile.lock
  docker/panw-iot/verify.py
Labels: Contribution

#27672 Update PrivX API base image to v34.0.1
  docker/privx-api/Dockerfile
  docker/privx-api/Pipfile
  docker/privx-api/Pipfile.lock
  docker/privx-api/build.conf
  docker/privx-api/verify.py
Labels: Contribution

#28307 [crypto] improve verify
  docker/crypto/verify.py
Labels: native image approved

#27829 Adding Sublime Docker Image
  .github/dependabot.yml
  docker/sublime/.gitignore
  docker/sublime/Dockerfile
  docker/sublime/Pipfile
  docker/sublime/Pipfile.lock
  docker/sublime/build.conf
Labels: Contribution

#28306 Native Image: Match dependencies, avoid discrepancies
  Pipfile
  Pipfile.lock
  docker/auth-utils/poetry.lock
  docker/crypto/Pipfile
  docker/crypto/Pipfile.lock
  docker/google-api-py3/Pipfile
  docker/google-api-py3/Pipfile.lock
  docker/netutils/poetry.lock
  docker/netutils/pyproject.toml
  docker/office-utils/Pipfile
  docker/office-utils/Pipfile.lock
  docker/py3-native/poetry.lock
  docker/py3-native/pyproject.toml
  docker/py3ews/Pipfile
  docker/py3ews/Pipfile.lock
  docker/sklearn/Pipfile
  docker/sklearn/Pipfile.lock
  utils/compare_dependency_constraints.py
Labels: native image approved, force-merge

#28562 regenereate deb
  docker/python3-deb/Dockerfile
Labels: native image approved
