Repository demisto/dockerfiles, pull requests merged in 2024-05, with the labels that each got.

#26351 add pydantic to `py3-tools`
  .github/dependabot.yml
  docker/auth-utils/poetry.lock
  docker/auth-utils/pyproject.toml
  docker/fastapi/Pipfile
  docker/fastapi/Pipfile.lock
  docker/py3-native/poetry.lock
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
  docker/python3-ubi/Pipfile
  docker/python3-ubi/Pipfile.lock
  docker/vendors-sdk/poetry.lock
  docker/vendors-sdk/pyproject.toml
Labels: native image approved, force-merge

#26453 fix to py3
  docker/py3-tools/Dockerfile
Labels: native image approved

#25783 add yara-python to taxii2 docker
  docker/py3-native/poetry.lock
  docker/py3-native/pyproject.toml
  docker/taxii2/Dockerfile
  docker/taxii2/verify.py
Labels: native image approved

#26504 Add pyzipper to py3-tools docker file
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
  docker/py3-tools/verify.py
Labels: native image approved

#26567 Update pytmv1 to 0.8.3 for demisto PR (Trend micro vision one #34456)
  docker/pytmv1/Pipfile.lock
  docker/pytmv1/verify.py
Labels: Contribution

#27036 [docker] - update netutils image
  docker/netutils/poetry.lock
  docker/netutils/pyproject.toml
  docker/netutils/verify.py
Labels: native image approved

#27233 Remove pyminizip dependency
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
Labels: native image approved
