Repository demisto/dockerfiles, pull requests merged in 2024-07, with the labels that each got.

#27235 rename the port.txt file to chrome_instances.tsv in the docker image
  docker/chromium/Dockerfile
  docker/chromium/Pipfile
  docker/chromium/Pipfile.lock
  docker/chromium/verify.py
  docker/py3-native/Dockerfile
  docker/py3-native/poetry.lock
  docker/py3-native/pyproject.toml
  docker/py3-native/verify.py
Labels: native image approved, force-merge

#28754 [py3-tools-ubi & py3-tools] Lock The `intezer_sdk` at 1.19.9
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
  docker/py3-tools/verify.py
Labels: native image approved

#25901 Update python3-ubi to 3.11
  docker/python3-ubi/Dockerfile
  docker/python3-ubi/Pipfile
  docker/python3-ubi/Pipfile.lock
Labels: native image approved

#25904 update alpine images to 3.11
  docker/python3/Dockerfile
  docker/python3/Pipfile
  docker/python3/Pipfile.lock
Labels: native image approved

#25905 update `python3-deb` to 3.11
  docker/python3-deb/Dockerfile
  docker/python3-deb/Pipfile
  docker/python3-deb/Pipfile.lock
Labels: native image approved

#25902 update `py3-tools-ubi` to 3.11
  .github/dependabot.yml
  docker/py3-tools-ubi/Dockerfile
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
Labels: native image approved

#28665 [Native & py3ews] Update `exchangelib` to 5.4.1
  docker/py3-native/poetry.lock
  docker/py3-native/pyproject.toml
  docker/py3ews/Pipfile
  docker/py3ews/Pipfile.lock
Labels: native image approved

#29690 [py3-tools] lock `paho-mqtt` = ^1.6.1
  docker/py3-tools-ubi/pyproject.toml
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
Labels: native image approved

#29696 add openssl
  docker/auth-utils/Dockerfile
  docker/auth-utils/verify.py
Labels: native image approved

#29738 python3 - update setuptools version
  docker/python3/Dockerfile
  docker/python3/verify.py
Labels: native image approved

#29737 python3-deb - update setuptools version
  docker/python3-deb/Dockerfile
  docker/python3-deb/Pipfile
  docker/python3-deb/Pipfile.lock
Labels: native image approved

#29736 python3-ubi - update setuptools version
  docker/python3-ubi/Dockerfile
Labels: native image approved

#29731 [intezer-sdk] Update To 1.21.3
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
  docker/py3-tools/Dockerfile
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
Labels: native image approved

#29825 update taxii2 and yolo-coco dockers
  docker/taxii2/Dockerfile
  docker/taxii2/Pipfile
  docker/taxii2/Pipfile.lock
  docker/yolo-coco/Dockerfile
  docker/yolo-coco/Pipfile
  docker/yolo-coco/Pipfile.lock
Labels: native image approved

#29725 Add files to create cyberchef image
  .github/dependabot.yml
  docker/cyberchef/.gitignore
  docker/cyberchef/Dockerfile
  docker/cyberchef/Pipfile
  docker/cyberchef/Pipfile.lock
  docker/cyberchef/bake.js
  docker/cyberchef/build.conf
  docker/cyberchef/magic.js
  docker/cyberchef/verify.py
Labels: Contribution

#29688 Trend pytmv1
  docker/pytmv1/Pipfile
  docker/pytmv1/Pipfile.lock
Labels: Contribution

#28425 add `poetry-plugin-export`
  .circleci/config.yml
  docker/dockerbuild/Pipfile
  docker/dockerbuild/Pipfile.lock
Labels: force-merge

#30385 tesseract - remove aom
  docker/tesseract/Dockerfile
Labels: native image approved

#30088 Deprecate nltk
  docker/deprecated_images.json
  docker/nltk/build.conf
Labels: force-merge

#30395 python3-ubi - Remove python3-setuptools-wheel
  docker/python3-ubi/Dockerfile
Labels: native image approved

#29877 Add `json2html` to py3-tools
  .github/dependabot.yml
  docker/py3-native/poetry.lock
  docker/py3-native/pyproject.toml
  docker/py3-tools/poetry.lock
  docker/py3-tools/pyproject.toml
  docker/py3-tools/verify.py
Labels: native image approved, Contribution

#30397 py3-tools-ubi - remove pyminizip
  docker/py3-tools-ubi/Dockerfile
  docker/py3-tools-ubi/poetry.lock
  docker/py3-tools-ubi/pyproject.toml
Labels: native image approved
