Repository demisto/dockerfiles, pull requests merged in 2024-12, with the labels that each got.

#34488 update parse email to 0.1.31
  docker/parse-emails/poetry.lock
Labels: native image approved, force-merge

#34504 Remove python3.9
  docker/chromium/Dockerfile
  docker/office-utils/Dockerfile
  docker/sane-doc-reports/Dockerfile
  docker/sane-pdf-reports/Dockerfile
Labels: native image approved

#34509 Upgrade perl and sqlite3
  docker/ml/Dockerfile
Labels: native image approved, force-merge

#34491 Update the python version in python3 dockerfile
  docker/python3/Dockerfile
  docker/python3/Pipfile
  docker/python3/Pipfile.lock
Labels: native image approved

#34513 Update python3-deb with 3.12
  docker/python3-deb/Dockerfile
  docker/python3-deb/Pipfile
  docker/python3-deb/Pipfile.lock
Labels: native image approved

#34550 update parse email to 0.1.32
  docker/parse-emails/poetry.lock
Labels: native image approved

#34502 Updating the crypto docker to use python 3.12
  docker/crypto/Dockerfile
  docker/crypto/Pipfile
  docker/crypto/Pipfile.lock
Labels: native image approved

#34507 Update py3ews with python3.12
  docker/py3ews/Dockerfile
  docker/py3ews/Pipfile
  docker/py3ews/Pipfile.lock
Labels: native image approved

#33314 infra docker files
  .circleci/config.yml
  .github/config.yml
  .gitignore
  .gitlab/.gitlab-ci.yml
  .gitlab/helper_functions.sh
  .hooks/bootstrap
  .pre-commit-config.yaml
  README.md
  docker/build_docker.sh
  docker/update-repository-info.sh
  poetry.lock
  poetry.toml
  pyproject.toml
  unit_tests/validate_deprecated_dockers_test.py
  unit_tests/verify_version_matching_test.py
Labels: native image approved

#34569 fix post slack message
  docker/build_docker.sh
  docker/post_github_comment.py
Labels: native image approved

#34710 Update docker image
  docker/xsoar-tools/Pipfile
  docker/xsoar-tools/Pipfile.lock
Labels: force-merge
