Repository demisto/dockerfiles, pull requests merged in 2025-02, with the labels that each got.

#35961 Confluent kafka avro (#35932)
  docker/vendors-sdk/poetry.lock
  docker/vendors-sdk/pyproject.toml
  docker/vendors-sdk/verify.py
Labels: Contribution

#35963 update parse-emails
  docker/parse-emails/poetry.lock
Labels: native image approved

#35964 The cyberintegrations library has been updated to version 0.7.6
  docker/vendors-sdk/poetry.lock
Labels: Contribution

#35997 update parse-emails
  docker/parse-emails/poetry.lock
Labels: native image approved

#36005 Updating the cyberintegrations library to version 0.7.7
  docker/vendors-sdk/poetry.lock
Labels: Contribution

#36015 Update cyberintegrations version
  docker/vendors-sdk/poetry.lock
Labels: Contribution

#35331 install gke
  docker/gitlab-content-ci/Dockerfile
Labels: force-merge

#36100 poetry change
  docker/gitlab-content-ci/Dockerfile
Labels: force-merge

#36125 add psutil to netutil
  docker/netutils/Dockerfile
  docker/netutils/poetry.lock
  docker/netutils/pyproject.toml
Labels: native image approved
