Repository demisto/dockerfiles, pull requests merged in 2025-01, with the labels that each got.

#34969 Revert the Python3 docker to 3.11
  docker/python3/Dockerfile
  docker/python3/Pipfile
  docker/python3/Pipfile.lock
Labels: native image approved

#35144 Update python3 docker image to Python 3.12
  docker/python3/Dockerfile
  docker/python3/Pipfile
  docker/python3/Pipfile.lock
Labels: native image approved

#34984 dockerfile - create a new/update a docker for the dockerfile build
  docker/gitlab-docker-ci/Dockerfile
  docker/gitlab-docker-ci/poetry.lock
  docker/gitlab-docker-ci/pyproject.toml
  docker/gitlab-docker-ci/verify.py
Labels: force-merge

#35870 Opencti version update
  docker/fastapi/Pipfile.lock
  docker/py-ews/Pipfile.lock
  docker/vendors-sdk/poetry.lock
  docker/zeep/Pipfile.lock
Labels: Contribution
